version: '3'
services:
  rtmp-server:
    image: tiangolo/nginx-rtmp
    container_name: rtmp-server
    ports:
      - "80:80"
      - "1935:1935"  # RTMP port
    volumes:
      - /$PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped